apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservizi-utenti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservizi-utenti
  template:
    metadata:
      labels:
        app: microservizi-utenti
    spec:
      containers:
        - name: microservizi-utenti
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: RABBITMQ_HOST
              value: rabbitmq.default.svc.cluster.local
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: guest
            - name: RABBITMQ_PASSWORD
              value: guest
          image: pievit/microservizi-utenti:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: microservizi-utenti
spec:
  selector:
    app: microservizi-utenti
  ports:
    - port: 8080
      targetPort: 8080
